# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

fastqfiles: "/data/BCI-EvoCa2/marc/anisha/fastqfiles/"
log_dir: "logs/"
genome: "/data/BCI-EvoCa2/marc/refs/hg19/ucsc.hg19.fasta"
binsize: "1000"
workdirectory: "/data/BCI-EvoCa2/marc/anisha/resultsnew/"


progressors: "A"
nonprogressors: "X,O"

readscutoff: "3e6"
